name: Format and build
on:
  pull_request:
    branches: [main]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        npm install
        npm run prettier:check
        npm run build
        cd src-tauri
        cargo check
        cargo format
