name: 🚀 Docker Image
on:
  workflow_dispatch:
jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
    - uses: actions/checkout@v4
    - name: metadata
      id: metadata
      run: |
        git fetch --all --tags
        TAG=$(git describe --tags)
        echo "tag=${TAG/-*}" >> $GITHUB_OUTPUT
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
      with:
        install: true
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & push prem
      run: >-
        docker buildx build --push
        --file Dockerfile
        --tag ghcr.io/premai-io/prem-app:latest
        --tag ghcr.io/premai-io/prem-app:${{ steps.metadata.outputs.tag }}
        --platform linux/arm64,linux/amd64 .
